export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const REGISTER_CREATED_SUCCESS = "REGISTER_CREATED_SUCCESS";

export const UPDATED_SUCCESS = "UPDATED_SUCCESS";
export const UPDATE_REQUEST = "UPDATE_REQUEST";

export const ADMIN_UPDATED_SUCCESS = "ADMIN_UPDATED_SUCCESS";
export const ADMIN_UPDATE_REQUEST = "ADMIN_UPDATE_REQUEST";

export const INPUT_DATA_TRANSFER = "INPUT_DATA_TRANSFER";
export const PRODUCT_DATA_TRANSFER = "PRODUCT_DATA_TRANSFER";
export const CLEAR_DATA_TRANSFER = "CLEAR_DATA_TRANSFER";

export const RECIPE_DATA = "RECIPE_DATA";
export const CLEAR_RECIPE_DATA = "CLEAR_RECIPE_DATA";

export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const CLEAR_ADD_INGREDIENTS = "CLEAR_ADD_INGREDIENTS";

export const SALE_ITEMS = "SALE_ITEMS";
export const CLEAR_SALE_ITEMS = "CLEAR_SALE_ITEMS";

export const UPDATE_UNITIES = "UPDATE_UNITIES";
export const CLEAR_UPDATE_UNITIES_DATA = "CLEAR_UPDATE_UNITIES_DATA";

export const UPDATE_SALES_STATUS = "UPDATE_SALES_STATUS";
export const CLEAR_UPDATE_SALES_STATUS_DATA = "CLEAR_UPDATE_SALES_STATUS_DATA";

/* Esta action vai manter os dados do login no local storage depois que este for feito. Sem ele
  esses dados desaparecerão quando a página for atualizada */
export const PERSIST_REHYDRATE = "persist/REHYDRATE";
